### PR TITLE
CMakeLists.txt: Add file weapons.json

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to Vega Strike: Upon the Coldest Sea.

Please answer the following:

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only

Issues:
- Please list any related issues
- Fixes https://github.com/vegastrike/Assets-Masters/issues/43

Purpose:
- What is this pull request trying to do? Fix the problem with vsUTCS as built using CMake, where the new file weapons.json is missing
- What release is this for? 0.9.x
- Is there a project or milestone we should apply this to? 0.9.x

### CODE REVIEW

**Review by BenjamenMeyer — APPROVED** [review]
Need this ported to 0.8.x too

**Comment by stephengtuggy** [comment]
> Need this ported to 0.8.x too

Really? Why's that?

**Comment by stephengtuggy** [comment]
Thanks to @evertvorster for providing the patch.

**Review by evertvorster — COMMENTED** [review]
All good, thanks for adding my name!

**Comment by BenjamenMeyer** [comment]
> > Need this ported to 0.8.x too
> 
> Really? Why's that?

Just thinking of a Arch related bug...but then Arch may be using master so probably not then.

**Comment by evertvorster** [comment]
Arch pulls from Asset-Production, then does a make & make install. 
It stands to reason that if Arch runs into a bug, anyone that builds from source will run into the same bug. 

Thanks for the fix, though.

**Comment by BenjamenMeyer** [comment]
I think I'm thinking of #697

**Pull request merged**
