### PR TITLE
CMakeLists.txt: Add file master_part_list.json

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to Vega Strike: Upon the Coldest Sea.

Please answer the following:

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only
- [X] This is an installer system change only

Issues:
- Please list any related issues
- Fixes https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/720

Purpose:
- What is this pull request trying to do? Add a missing file to the list of files to install
- What release is this for? 0.9.x
- Is there a project or milestone we should apply this to? 0.9.x

### CODE REVIEW

**Comment by royfalk** [comment]
I admit this makes me uneasy. Here's a file I never knew existed and a crash I didn't catch.
Did I not see it because of cmake cache? 
I'd appreciate if you'd write a few lines about it and maybe update the PR validation guide.
Anyway, LGTM.

**Review by royfalk — APPROVED** [review]
LGTM.

**Comment by evertvorster** [comment]
I can only guess here, but as I only point vegastrike at the directory that is made by the install part of CMakeList I would catch errors like these. My question now is, how are the other packages not affected? Surely they only install what is specified in Cmake?

**Comment by BenjamenMeyer** [comment]
> I can only guess here, but as I only point vegastrike at the directory that is made by the install part of CMakeList I would catch errors like these. My question now is, how are the other packages not affected? Surely they only install what is specified in Cmake?

We've just started changing things in VS Engine master to use the JSON by default; other stuff still relies on the CSV. We should be installing the JSON too.

**Review by BenjamenMeyer — APPROVED** [review]

**Pull request merged**
