### PR TITLE
Hidden asteroid load fix

### PR DESCRIPTION
**Pull request by evertvorster**
Unit name missing from Units.csv. There was a "neutral" version of this one, should be good enough for a copy

### CODE REVIEW

**Comment by nabaco** [comment]
Hi @evertvorster, I resolved the merge conflict that arose due to previous merges. Please make sure I resolved it correctly and we'll merge this change.

**Comment by evertvorster** [comment]
The HiddenAsteroid base does show up while reading the units.csv file with the UnitConverter. This to means that the HiddenAsteroid entry is in there correctly, as both the game engine and the UnitConverter interpret the units.csv file in the same way. 

This PR should be good to go. I'll make a test sector with one of these bases in and see if it shows up. I'll learn a neat little trick in the process.

**Comment by evertvorster** [comment]
Proof it works:

Screenshot_20200723_190241

**Comment by stephengtuggy** [comment]
That's pretty cool! I don't know that I've ever seen one of those.

**Pull request merged**
