### PR TITLE
CI: Sync with changes from 0.7.x

### LINKED ISSUE #43: Move from Travis-CI to GitHub Actions
This is a the Assets Production version of 
https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/382.

### PR DESCRIPTION
**Pull request by BenjamenMeyer**
the 0.7.x branch has the most up-to-date methods; sync them back
to master

Thank you for submitting a pull request and becoming a contributor to Vega Strike: Upon the Coldest Sea.

Please answer the following:

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only
- [x] CI-only

Issues:
- #43 

Purpose:
Sync the GH actions from 0.7.x to master (0.8.x)
Closes #43

### CODE REVIEW

**Review by Loki1950 — APPROVED** [review]
Looks OK

**Review by stephengtuggy — CHANGES_REQUESTED** [review]
Looks good so far. However, I think we also need to apply changes to `CMakeLists.txt`; to `script/cibuild`; and to `script/docker-entrypoint.sh`, replacing TRAVIS variables with their equivalents. You may just be able to cherry-pick commit https://github.com/vegastrike/Assets-Production/commit/fc5bc0a829b121ddc83411c84f2819986c8076f9

**Comment by BenjamenMeyer** [comment]
@stephengtuggy thanks. I'll take a look at those too before merging this

**Comment by BenjamenMeyer** [comment]
@stephengtuggy okay - cherry picked fc5bc0a829b121ddc83411c84f2819986c8076f9 but after I had updated some of it already (thus the two commits) instead of one.

**Review by stephengtuggy — APPROVED** [review]
Looks good!

**Pull request merged**
