### PR TITLE
CMake do not require any compiler

### PR DESCRIPTION
**Pull request by susnux**
Set project language to NONE to disable CMake compiler check

There is nothing to compile here, so there is no need for a C and a C++ compiler.

### CODE REVIEW

**Review by BenjamenMeyer — CHANGES_REQUESTED** [review]
We need more information about the files under `programs` before approving this.

**Comment by stephengtuggy** [comment]
This PR breaks the CodeQL CI job. CodeQL can no longer determine what language(s) the project uses. Is this acceptable?

**Comment by susnux** [comment]
> This PR breaks the CodeQL CI job. CodeQL can no longer determine what language(s) the project uses. Is this acceptable?

You can set the language manually for CodeQL in the `codeql.yml` file. Then it should work again.

**Comment by BenjamenMeyer** [comment]
@susnux please merge in master as the CodeQL stuff has been updated with #68

**Review by stephengtuggy — APPROVED** [review]
Looks good to me. I think I'll go ahead and merge this.

**Pull request merged**
