### PR TITLE
CMakeLists.txt, main_menu.py, readme.txt, vsinstall.sh: Bump version to 0.8.1

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to Vega Strike: Upon the Coldest Sea.

Please answer the following:

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only

Issues:
- Please list any related issues

Purpose:
- What is this pull request trying to do? Bump the minor version number in preparation for a new 0.8.x release
- What release is this for? 0.8.1, naturally :-)
- Is there a project or milestone we should apply this to? 0.8.x

### CODE REVIEW

**Comment by evertvorster** [comment]
Does SVN still work?
Amazing. I would recommend you switch over to git. Sure, there is a bit of a learning curve, but it's much kinder on your network once you have the entire repo.
There might be a way to generate the patch files from Github, it's something I will have to check.
I am assuming you are at 0.8.0?

**Comment by LifWirser** [comment]
I tried using svn with addr from GH 0.8.x which is [https://github.com/vegastrike/Vega-Strike-Engine-Source.git](url) and srarted recieving assets-0.6.4 or somesuch . I THEN D/LED THE ZIP

**Comment by stephengtuggy** [comment]
@LifWirser SVN will not work any more. You have to use Git.

**Comment by BenjamenMeyer** [comment]
> I don't mind bumping ver#
> 
> Just one question, will patch files be available? I tried getting 0.8.x via svn and was getting all previos asset trees

The SVN code is only what was done in SourceForge, and it outdated. The original devs/maintainers that ran the SF account migrated the code to hear in Git before the current team of maintainers took over. We are only operating using `git` with GitHub. I know there is a git integration for git users to work with SVN; but I'm not aware of any that go in reverse.

The engine Git repo also is disconnected (purposefully) from the assets repository, unlike the old SVN repo. We did this to help ensure the engine development works with multiple assets and we work with PWCU and VS:UtCS assets.

**Pull request merged**
