### PR TITLE
Complementing changes to engine 'Implement Drive and Afterburner'

### PR DESCRIPTION
**Pull request by royfalk**
This complements https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/896
- Add support for AfterburnerUpgrade
- Modify Llama.begin with reactor03 and correct SPEC capacitor. This will allow SPEC with game start. 
- Remove Llama.begin from units.json.

Thank you for submitting a pull request and becoming a contributor to Vega Strike: Upon the Coldest Sea.

Please answer the following:

Code Changes:
- [x] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation

### CODE REVIEW

**Comment by evertvorster** [comment]
Hi there. 
I installed the task_drives branch of Assets, and patched it with #128 
For the engine I installed branch task_real_drive_comp of Engine, and patched that with #897 from the Engine repo. 

This PR does solve the inability to buy a jump drive, and allows you to run SPEC continuously. 
It's also a prerequisite to allow the other PR in engine to work. 

So, as far as that goes, this PR is good to go from my perspective. 

I am still having the strange issue where I thought that I had no flight controls when loading a newly saved new campaign. I was wrong, there is flight controls, just very, very little.
This points to silly values in the save file, and upon inspection there are indeed silly values. 
I see that in the save file created with this PR the unit is still called llama.begin, and  rather than one value in the various governors (45) for the flight controls there are now three values separated by a slash. (0.01/0.01/0.01) 

Serialized xml for a saved game created by the 0.8.x version of the game engine:
[Llama.begin.csv](https://github.com/user-attachments/files/17517247/Llama.begin.csv)


Serialized xml for a saved game created by the current PR in Assets and Engine:
[Llama.begin.csv](https://github.com/user-attachments/files/17517260/Llama.begin.csv)

With these branches installed, the screen variable in vegastrike.config is being ignored, not sure if that will go away when I run master again.

**Comment by royfalk** [comment]
> there are now three values separated by a slash. (0.01/0.01/0.01)

That's a bug introduced by #893. I'll take a look at it. You can go ahead and open a bug and assign it to me.

> With these branches installed, the screen variable in vegastrike.config is being ignored, not sure if that will go away when I run master again.

Yes it is. You should now edit config.json. Same for resolution.
I'm in the process of moving away from vs.config (xml) into more readable json files. I'll also dump all the obscure advanced settings into a separate 'advanced' file.

**Comment by evertvorster** [comment]
Thanks for the tip. I created the requested bug report. 

As for editing the config.json...
There seems to be almost nothing in /usr/share/vegastrike/config.json:
```
{
"general": {},

"graphics": {
    "resolution_x": 2560,
    "resolution_y": 1600,
    "screen": 0
},
"advanced": {}
}
```

There is no other config.json anywhere that I could find that is related to vegastrike. 
Some guidance on how to edit this file, and where it is supposed to be located, as well as some examples would be greatly appreciated.

**Comment by royfalk** [comment]
> There seems to be almost nothing in /usr/share/vegastrike/config.json

It's a work in progress. You can't just move everything over. The C++ code needs to reflect this. 

Also, I plan on moving things slowly and thinking about what goes where.

Also renaming and deleting settings.

For now, what you can edit is what you see.

**Comment by royfalk** [comment]
I've moved the changes to #134.
With the introduction of the rather drastic #133 , changes made to the old asset units file are very out of date.
Specifically, we made numerous changes to both units.json and ships.json with a script. 

Also, it seems we have two PR's to match https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/896, so I picked #134  instead.

Closing.

**Pull request closed without merging**
