### PR TITLE
Move ship view and upgrade view to python

### PR DESCRIPTION
**Pull request by royfalk**
This only takes effect when the engine PR ([#904](https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/904)) is also merged.

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation. Performed extensive tests of the code in question. Minimal game play tests.

Issues:
- Undocumented reactor tweak - description is 'capacitor capacity'. Reword.
- Radar is in radians. Convert to degrees for a clearer description.
- Mass/Space required is indented for some reason.

### CODE REVIEW

**Comment by evertvorster** [comment]
Hi there! 
At the moment what I am doing is to just pull whatever branch you are working on, and build that to play test it. 
What is the best way of merging this and the engine PR at the same time so that I can test this properly?

**Comment by royfalk** [comment]
These are two separate repos. You don't need (and can't) merge them. 
One is assets. The other is engine.

Also, this doesn't fix any existing game play issues in master.
It moves the player info (relations with other factions screen) and upgrade info (part info in ship upgrades).

**Comment by evertvorster** [comment]
Hi there!
Thanks for the pointer. I'm now building both Assets and Engine with the requested branches, and will give them a go. 
Anything in particular that I should be looking for?

**Comment by royfalk** [comment]
> Anything in particular that I should be looking for?

player info (relations with other factions screen) and upgrade info (part info in ship upgrades).

**Comment by evertvorster** [comment]
Hi there!
Just had a quick look. When starting a new campaign, the info looks good and normal. Ship info looks good as well. 
However, when loading a saved game from a while ago, I have a negative kill count. In this save game I somehow managed to annoy the ConFed, and when loading with this branch is where I see the negative one kill counts for two of the factions.

Here is the save file for reference:
[0.9.x_Advanced_Trade_Vendetta.zip](https://github.com/user-attachments/files/17700020/0.9.x_Advanced_Trade_Vendetta.zip)

**Review by BenjamenMeyer — APPROVED** [review]

**Comment by royfalk** [comment]
> In this save game I somehow managed to annoy the ConFed

I just fixed it on the assets/script side. According to the records, you have one kill - a confed.

**Comment by evertvorster** [comment]
Yup, I suppose that would do it. I think I picked up that kill as part of the last mission that you get in the beginning of the game. 
In any case, I am now building this branch of Assets, and will use it to test the branches in Engine. Many thanks for the hard work you are putting into this.

**Review by evertvorster — APPROVED** [review]
This now has the proper kill counts and relations as when compared with git master, and in my mind it is good to go.

**Pull request merged**
