### PR TITLE
Fix Campaign Cargo py3 range issue on master

### PR DESCRIPTION
**Pull request by stephengtuggy**
Thank you for submitting a pull request and becoming a contributor to Vega Strike: Upon the Coldest Sea.

Please answer the following:

Code Changes:
- [Pending] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only

Issues:
- Please list any related issues
- Closes https://github.com/vegastrike/Assets-Masters/issues/32

Purpose:
- What is this pull request trying to do? Port #76 to master
- What release is this for? 0.9.x
- Is there a project or milestone we should apply this to? 0.9.x

### CODE REVIEW

**Review by Loki1950 — APPROVED** [review]
looks good

**Comment by stephengtuggy** [comment]
Thanks, @Loki1950 . I'll probably play test this briefly, and make sure that the fix is working as intended, then merge it.

**Review by BenjamenMeyer — APPROVED** [review]
Looks like a change pulled from 0.8.x

**Comment by stephengtuggy** [comment]
All right. I've done enough play testing to satisfy myself that this fix is working as intended. Merging.

**Pull request merged**
