### PR TITLE
Convert weapon_list to weapons.json

### PR DESCRIPTION
**Pull request by royfalk**
Including generating script and actual file.
Note that this change and the previous one to units will break Wing Commander.

Code Changes:
- [Not Yet] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation

Issues:
- There are previous issues in the weapon_list that should be addressed at some point.
- The JSON library does not conform to the standard, making the code sloppier than I would have liked.
- Old files (units.csv and weapon_list.xml) have not been deleted yet.

### CODE REVIEW

**Review by BenjamenMeyer — COMMENTED** [review]
Assuming the `weapons.json` is correct.

**Comment by BenjamenMeyer** [comment]
@royfalk @ermo we need something similar for PWCU

**Comment by royfalk** [comment]
> @royfalk @ermo we need something similar for PWCU

Simply run convert.py (weapon_list.xml) and parser.py (units.csv) and it will generate it for you.

**Comment by royfalk** [comment]
> Assuming the `weapons.json` is correct.

I did not run a complete comparison of the two, but I did spot check and they seem identical. Also, the script is pretty simple so I don't see a lot of places where it can go wrong.

**Comment by stephengtuggy** [comment]
> > @royfalk @ermo we need something similar for PWCU
> 
> Simply run convert.py (weapon_list.xml) and parser.py (units.csv) and it will generate it for you.

Yeah, I'm working on the units conversion as we speak.

**Comment by stephengtuggy** [comment]
Here's the draft pull request for the units conversion for PWCU: https://github.com/pwcu/privateer_wcu/pull/9

**Review by BenjamenMeyer — APPROVED** [review]

**Pull request merged**
