### PR TITLE
Removes the debug warnings from the console

### PR DESCRIPTION
**Pull request by evertvorster**
This simple little edit hides the spammy debug error messages in the console

### CODE REVIEW

**Comment by evertvorster** [comment]
The messages are debug messages. There really should be a --debug switch that can be thrown to turn messages like this on. 

Still, for a production we don't need debug messages scrolling around the console obscuring real errors.

**Comment by nabaco** [comment]
@evertvorster - is possible for you to add the switch, instead of just commenting the logs?
You could add just the logic for the switch, and we'll deal later with integrating it with our build system and/or engine.

**Comment by evertvorster** [comment]
@nabaco, I am not a coder, and would not know where to start in making an ifdef for this. 

Since I have just commented out the debug message, it's easy enough for a troubleshooter in the future to re-enable to hunt down bugs.

My apologies for not being able to provide a nicer solution to this at this point in time.

**Comment by BenjamenMeyer** [comment]
If they're just debug messages then we should send them to the log system at the debug level and the config will take care of it.

**Comment by nabaco** [comment]
@BenjamenMeyer do you know how to do that in the python files?

**Comment by BenjamenMeyer** [comment]
@nabaco not sure how it connects back to C/C++ land, but in Python:
```python
import logging

LOG = logging.getLogger(__name__)

LOG.debug("message")
```

If we could figure out how that connects with Boost and C++ to dump into the logs there that would be awesome. I'm sure there's a way, just haven't done it myself. Boost Python docs might inform us.

**Comment by nabaco** [comment]
@stephengtuggy @BenjamenMeyer - so what's our verdict on this PR? @evertvorster clearly stated that he's not up for the job to make the switch?
Does one of you guys wish to pick this up?
If not, I say let's reject this PR, and open a ticket based on it, to be implemented in better times.

**Comment by evertvorster** [comment]
@stephengtuggy OK, which is better... spamming the console with useless error messages making the game look unstable, or a nice calm console? Sure, a debug switch can be added, and we can stick that in as an issue on this Repo to be corrected, and reference this PR as a place to start. Would that not achieve both our goals?

**Comment by stephengtuggy** [comment]
@evertvorster Hmm, I see your point.

At a minimum, I have filed #8 https://github.com/vegastrike/Vega-Strike-Engine-Source/issues/167 and https://github.com/vegastrike/Assets-Masters/issues/13 . I guess that's good enough for now. I'm okay with merging this PR.

@BenjamenMeyer @nabaco @Loki1950 what do you think?

**Comment by stephengtuggy** [comment]
@evertvorster this PR fixed https://github.com/vegastrike/Assets-Masters/issues/10 , right?

**Comment by evertvorster** [comment]
Indeed it did. I closed that issue. :)

**Pull request merged**
