### PR TITLE
Add missing config.json to support #892

### PR DESCRIPTION
**Pull request by royfalk**
This is the complementing config.json for [#892](https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/892).

Please answer the following:

Code Changes:
- [x] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation

Issues:
- This temporarily deprecates the settings app.

### CODE REVIEW

**Comment by royfalk** [comment]
I don't think the python CodeQL is related to my JSON file.

**Review by evertvorster — CHANGES_REQUESTED** [review]
When you add a new file, you also need to add that file to CMakeLists.txt, otherwise it simply does not get installed when you make install. 

It would make sense to make that change to CMakeLists.txt as part of this pull request.

**Comment by evertvorster** [comment]
Yup, that did it, vegastrike now launches with this pull request. 
So, it is all good, and this pull request should be merged. 

;)

**Review by evertvorster — APPROVED** [review]

**Comment by royfalk** [comment]
> Yup, that did it, vegastrike now launches with this pull request. So, it is all good, and this pull request should be merged.
> 
> ;)

I'm still waiting on confirmation from @BenjamenMeyer on the codeQL stuff.

**Comment by royfalk** [comment]
I don't think the python CodeQL is related to my JSON file. However, this error is absent from my other PR and is recurring. Rerunning the process doesn't fix it.

@BenjamenMeyer can you shed some light here? Did I get in the middle of two of your PR's. There's nothing here for me to work with.

**Review by BenjamenMeyer — APPROVED** [review]

**Comment by BenjamenMeyer** [comment]
Might be we need to update the GitHub Action...it's having trouble reading some results or something...not sure what the SARIF is. But just a guess.

It's on the Python module so no, not related to your code afaict

**Comment by royfalk** [comment]
OK. I'm merging this. We'll monitor this further.

**Pull request merged**
